apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q4xfje1lw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q4xfje1lw-python 
  name: q4xfje1lw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q4xfje1lw-python 
